"""Criando tabelas

Revision ID: 9863773f3cb0
Revises: 1b5925595d7f
Create Date: 2024-08-29 22:46:22.774840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9863773f3cb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('USUARIO',
    sa.Column('id_usuario', sa.BigInteger(), nullable=False),
    sa.Column('nome_completo', sa.String(length=50), nullable=False),
    sa.Column('data_nascimento', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('senha', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('CARTAO_CREDITO',
    sa.Column('id_cartao_credito', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('limite', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('id_usuario', sa.BigInteger(), nullable=False),
    sa.Column('nome_icone', sa.String(length=100), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('limite_disponivel', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['USUARIO.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_cartao_credito'),
    sa.UniqueConstraint('nome', 'id_usuario', name='unique_nome_cartao')
    )
    op.create_table('CATEGORIA',
    sa.Column('id_categoria', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('tipo_categoria', sa.Enum('FIXA', 'VARIAVEL', name='tipocategoria'), nullable=False),
    sa.Column('modelo_categoria', sa.Enum('DESPESA', 'RECEITA', name='tipomovimentacao'), nullable=False),
    sa.Column('id_usuario', sa.BigInteger(), nullable=False),
    sa.Column('valor_categoria', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('nome_icone', sa.String(length=100), nullable=True),
    sa.Column('ativo', sa.Boolean, nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['USUARIO.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_categoria'),
    sa.UniqueConstraint('nome', 'id_usuario', name='unique_nome_categoria')
    )
    op.create_table('CONTA',
    sa.Column('id_conta', sa.BigInteger(), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('tipo_conta', sa.String(length=100), nullable=False),
    sa.Column('id_usuario', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=500), nullable=False),
    sa.Column('nome_icone', sa.String(length=100), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('saldo', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['USUARIO.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_conta'),
    sa.UniqueConstraint('nome', 'id_usuario', name='unique_nome_conta')
    )
    op.create_table('PARENTE',
    sa.Column('id_parente', sa.BigInteger(), nullable=False),
    sa.Column('grau_parentesco', sa.String(length=100), nullable=True),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('id_usuario', sa.BigInteger(), nullable=False),
     sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['USUARIO.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_parente')
    )
    op.create_table('FATURA',
    sa.Column('id_fatura', sa.BigInteger(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=True),
    sa.Column('data_fechamento', sa.Date(), nullable=True),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('id_conta', sa.BigInteger(), nullable=True),
    sa.Column('id_cartao_credito', sa.BigInteger(), nullable=True),
    sa.Column('fatura_gastos', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_cartao_credito'], ['CARTAO_CREDITO.id_cartao_credito'], ),
    sa.ForeignKeyConstraint(['id_conta'], ['CONTA.id_conta'], ),
    sa.PrimaryKeyConstraint('id_fatura')
    )
    op.create_table('MOVIMENTACAO',
    sa.Column('id_movimentacao', sa.BigInteger(), nullable=False),
    sa.Column('valor', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('tipoMovimentacao', sa.Enum('DESPESA', 'RECEITA', name='tipomovimentacao'), nullable=False),
    sa.Column('forma_pagamento', sa.Enum('DEBITO', 'CREDITO', 'DINHEIRO', name='formapagamento'), nullable=False),
    sa.Column('condicao_pagamento', sa.Enum('A_VISTA', 'PARCELADO', 'RECORRENTE', name='condicaopagamento'), nullable=False),
    sa.Column('datatime', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('quantidade_parcelas', sa.BigInteger(), nullable=True),
    sa.Column('consolidado', sa.String(length=100), nullable=False),
    sa.Column('tipo_recorrencia', sa.String(length=100), nullable=True),
    sa.Column('recorrencia', sa.String(length=100), nullable=True),
    sa.Column('data_pagamento', sa.Date(), nullable=False),
    sa.Column('id_conta', sa.BigInteger(), nullable=True),
    sa.Column('id_categoria', sa.BigInteger(), nullable=True),
    sa.Column('id_fatura', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['CATEGORIA.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_conta'], ['CONTA.id_conta'], ),
    sa.ForeignKeyConstraint(['id_fatura'], ['FATURA.id_fatura'], ),
    sa.PrimaryKeyConstraint('id_movimentacao')
    )
    op.create_table('divide',
    sa.Column('id_parente', sa.BigInteger(), nullable=False),
    sa.Column('id_movimentacao', sa.BigInteger(), nullable=False),
    sa.Column('valor', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_movimentacao'], ['MOVIMENTACAO.id_movimentacao'], ),
    sa.ForeignKeyConstraint(['id_parente'], ['PARENTE.id_parente'], ),
    sa.PrimaryKeyConstraint('id_parente', 'id_movimentacao')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('divide')
    op.drop_table('MOVIMENTACAO')
    op.drop_table('FATURA')
    op.drop_table('PARENTE')
    op.drop_table('CONTA')
    op.drop_table('CATEGORIA')
    op.drop_table('CARTAO_CREDITO')
    op.drop_table('USUARIO')
    # ### end Alembic commands ###
