"""criando tabelas

Revision ID: bde03a7f99bf
Revises: d32d708f0489
Create Date: 2024-08-18 19:09:30.183792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bde03a7f99bf'
down_revision = 'd32d708f0489'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
