"""adicionando descrição como null

Revision ID: c0de427ddd6b
Revises: 9863773f3cb0
Create Date: 2024-08-31 11:55:18.546153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0de427ddd6b'
down_revision = '9863773f3cb0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
